# Create PRs to automatically upgrade dependencies.

version: 2
updates:

- package-ecosystem: 'cargo'
  directory: '/'
  schedule:
    # NOTE: Before Dependabot runs, we perform simple upgrades automatically using
    # the `upgrade_deps.yml` workflow, which runs at 03:00 UTC.
    interval: 'weekly'
    day: 'monday'
    time: '05:00'

- package-ecosystem: 'github-actions'
  directory: '/'
  schedule:
    interval: 'daily'
  ignore:
    # Specific version pinned for testing toolchain compatibility.
    - dependency-name: "dtolnay/rust-toolchain"
